package View;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 824130958
 */
public class TelaEsqueceuSenha extends javax.swing.JFrame {

    /**
     * Creates new form TelaEsqueceuSenha
     */
    public TelaEsqueceuSenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Panelazul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BTSalvar = new javax.swing.JButton();
        LBcofirmenovasenha = new javax.swing.JLabel();
        LBnovasenha = new javax.swing.JLabel();
        TXTFCofirmenovasenha = new javax.swing.JTextField();
        TXTFemail = new javax.swing.JTextField();
        TXTFNovasenha = new javax.swing.JTextField();
        LBemail = new javax.swing.JLabel();
        LBredefinasuasenha = new javax.swing.JLabel();
        LBesqueceusenha = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1160, 720));
        jPanel1.setLayout(null);

        Panelazul.setBackground(new java.awt.Color(75, 109, 190));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Blue Flat Color Ui Login Page Desktop Prototype (2).png"))); // NOI18N

        javax.swing.GroupLayout PanelazulLayout = new javax.swing.GroupLayout(Panelazul);
        Panelazul.setLayout(PanelazulLayout);
        PanelazulLayout.setHorizontalGroup(
            PanelazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelazulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelazulLayout.setVerticalGroup(
            PanelazulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelazulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jPanel1.add(Panelazul);
        Panelazul.setBounds(0, 0, 580, 720);

        BTSalvar.setBackground(new java.awt.Color(75, 109, 190));
        BTSalvar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        BTSalvar.setForeground(new java.awt.Color(255, 255, 255));
        BTSalvar.setText("SALVAR");
        BTSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(BTSalvar);
        BTSalvar.setBounds(720, 600, 320, 70);

        LBcofirmenovasenha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LBcofirmenovasenha.setText("CONFIRME NOVA SENHA");
        jPanel1.add(LBcofirmenovasenha);
        LBcofirmenovasenha.setBounds(610, 470, 240, 22);

        LBnovasenha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LBnovasenha.setText("NOVA SENHA");
        jPanel1.add(LBnovasenha);
        LBnovasenha.setBounds(610, 350, 140, 22);

        TXTFCofirmenovasenha.setBackground(new java.awt.Color(237, 237, 237));
        TXTFCofirmenovasenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TXTFCofirmenovasenha.setText("Confirme Nova Senha");
        TXTFCofirmenovasenha.setBorder(null);
        jPanel1.add(TXTFCofirmenovasenha);
        TXTFCofirmenovasenha.setBounds(610, 510, 470, 57);

        TXTFemail.setBackground(new java.awt.Color(237, 237, 237));
        TXTFemail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TXTFemail.setText("E-mail");
        TXTFemail.setBorder(null);
        jPanel1.add(TXTFemail);
        TXTFemail.setBounds(610, 270, 470, 57);

        TXTFNovasenha.setBackground(new java.awt.Color(237, 237, 237));
        TXTFNovasenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TXTFNovasenha.setText("Nova Senha");
        TXTFNovasenha.setBorder(null);
        jPanel1.add(TXTFNovasenha);
        TXTFNovasenha.setBounds(610, 380, 470, 57);

        LBemail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LBemail.setText("E-MAIL");
        jPanel1.add(LBemail);
        LBemail.setBounds(610, 230, 70, 22);

        LBredefinasuasenha.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LBredefinasuasenha.setText("Redefina sua Senha");
        jPanel1.add(LBredefinasuasenha);
        LBredefinasuasenha.setBounds(770, 160, 240, 28);

        LBesqueceusenha.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        LBesqueceusenha.setText("Esqueceu a Senha?");
        jPanel1.add(LBesqueceusenha);
        LBesqueceusenha.setBounds(660, 100, 470, 56);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEsqueceuSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTSalvar;
    private javax.swing.JLabel LBcofirmenovasenha;
    private javax.swing.JLabel LBemail;
    private javax.swing.JLabel LBesqueceusenha;
    private javax.swing.JLabel LBnovasenha;
    private javax.swing.JLabel LBredefinasuasenha;
    private javax.swing.JPanel Panelazul;
    private javax.swing.JTextField TXTFCofirmenovasenha;
    private javax.swing.JTextField TXTFNovasenha;
    private javax.swing.JTextField TXTFemail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
